name: Release
on:
  pull_request:
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true # Condition
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
      - name: Install Dependencies
        run: bun install
      # - name: lint
      #   run: bun lint
      # - name: test
      #   run: bun test
      - name: release
        run: bun release
